version: "3.8"

services:
  # 1. Service ของ Traefik
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - TZ=${TZ}
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/traefik/certs:/etc/traefik/certs:ro
      - ./infra/traefik/dynamic:/etc/traefik/dynamic:ro
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"

  # 2. Service ตัวอย่าง whoami
  whoami:
    image: "traefik/whoami"
    container_name: "whoami-app"
    restart: unless-stopped
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend"
      - "traefik.http.services.whoami-app.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"

  # 3. Infisical Backend Service
  infisical:
    container_name: infisical-backend
    image: infisical/infisical:latest
    restart: unless-stopped
    pull_policy: always
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
      - DB_CONNECTION_URI=${INFISICAL_DB_CONNECTION_URI}
      - REDIS_URL=redis://redis:6379
      - SITE_URL=https://infisical.${DOMAIN}
      - NODE_ENV=production
      - ALLOW_INTERNAL_IP_CONNECTIONS=true
      - INFISICAL_POSTGRES_USER=${INFISICAL_POSTGRES_USER}
      - INFISICAL_POSTGRES_PASSWORD=${INFISICAL_POSTGRES_PASSWORD}
      - INFISICAL_POSTGRES_DB=${INFISICAL_POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend"
      - "traefik.http.services.infisical-backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.infisical.rule=Host(`infisical.${DOMAIN}`)"
      - "traefik.http.routers.infisical.entrypoints=websecure"
      - "traefik.http.routers.infisical.tls=true"

  # 4. Redis Caching Service
  redis:
    container_name: infisical-redis
    image: redis:alpine
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
    networks:
      - backend
    labels:
      - "traefik.enable=false"

  # 5. PostgreSQL Database Service
  db:
    container_name: postgres-db
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
      - INFISICAL_POSTGRES_DB=${INFISICAL_POSTGRES_DB}
      - INFISICAL_POSTGRES_USER=${INFISICAL_POSTGRES_USER}
      - INFISICAL_POSTGRES_PASSWORD=${INFISICAL_POSTGRES_PASSWORD}
      - PREFECT_POSTGRES_USER=${PREFECT_POSTGRES_USER}
      - PREFECT_POSTGRES_PASSWORD=${PREFECT_POSTGRES_PASSWORD}
      - PREFECT_POSTGRES_DB=${PREFECT_POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - backups:/backups:rw
      - ./infra/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    networks:
      - backend
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

  # 6. Automated Database Backup Service
  #  db-backup:
  #    container_name: postgres-db-backup
  #    image: prodrigestivill/postgres-backup-local
  #    restart: unless-stopped
  #    depends_on:
  #      - db
  #    environment:
  #      - POSTGRES_HOST=db
  #      - POSTGRES_DB=${POSTGRES_DB}
  #      - POSTGRES_USER=${POSTGRES_USER}
  #      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #      - SCHEDULE=${BACKUP_SCHEDULE}
  #      - BACKUP_KEEP_DAYS=7
  #      - BACKUP_KEEP_WEEKS=4
  #      - BACKUP_KEEP_MONTHS=6
  #    volumes:
  #      - backups:/backups
  #    networks:
  #      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - pgadmin:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN}`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls=true"
  prefect-migrate:
    container_name: prefect-migrate
    image: prefecthq/prefect:3-latest
    depends_on:
      db:
        condition: service_healthy
    command: prefect server database upgrade -y
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL}
      - PREFECT_API_DATABASE_TIMEOUT=600
    networks:
      - backend
    labels:
      - "traefik.enable=false"

  prefect-api:
    container_name: prefect-api
    image: prefecthq/prefect:3-latest
    depends_on:
      prefect-migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: prefect server start --host 0.0.0.0 --no-services
    environment:
      - PREFECT_UI_URL=${PREFECT_UI_URL}
      - PREFECT_UI_API_URL=${PREFECT_UI_API_URL}
      - PREFECT_UI_SERVE_BASE=${PREFECT_UI_SERVE_BASE}
      - PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL}
      - PREFECT_API_DATABASE_MIGRATE_ON_START=${PREFECT_API_DATABASE_MIGRATE_ON_START}
      - PREFECT_MESSAGING_BROKER=${PREFECT_MESSAGING_BROKER}
      - PREFECT_MESSAGING_CACHE=${PREFECT_MESSAGING_CACHE}
      - PREFECT_SERVER_EVENTS_CAUSAL_ORDERING=${PREFECT_SERVER_EVENTS_CAUSAL_ORDERING}
      - PREFECT_SERVER_CONCURRENCY_LEASE_STORAGE=${PREFECT_SERVER_CONCURRENCY_LEASE_STORAGE}
      - PREFECT_REDIS_MESSAGING_HOST=${PREFECT_REDIS_MESSAGING_HOST}
      - PREFECT_REDIS_MpgadminESSAGING_PORT=${PREFECT_REDIS_MESSAGING_PORT}
    ports:
      - "4200"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend" # บอก Traefik ให้ใช้ network นี้
      # --- สร้าง Router ที่ชี้ไปที่ port 4200 (UI และ API) ---
      - "traefik.http.routers.prefect.rule=Host(`prefect.${DOMAIN}`)"
      - "traefik.http.routers.prefect.entrypoints=websecure"
      - "traefik.http.routers.prefect.tls=true"
      - "traefik.http.services.prefect-svc.loadbalancer.server.port=4200"
      - "traefik.http.routers.prefect.service=prefect-svc"

  prefect-background:
    container_name: prefect-background
    image: prefecthq/prefect:3-latest
    depends_on:
      prefect-migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: prefect server services start
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL}
      - PREFECT_API_DATABASE_MIGRATE_ON_START=${PREFECT_API_DATABASE_MIGRATE_ON_START}
      - PREFECT_MESSAGING_BROKER=${PREFECT_MESSAGING_BROKER}
      - PREFECT_MESSAGING_CACHE=${PREFECT_MESSAGING_CACHE}
      - PREFECT_SERVER_EVENTS_CAUSAL_ORDERING=${PREFECT_SERVER_EVENTS_CAUSAL_ORDERING}
      - PREFECT_SERVER_CONCURRENCY_LEASE_STORAGE=${PREFECT_SERVER_CONCURRENCY_LEASE_STORAGE}
      - PREFECT_REDIS_MESSAGING_HOST=${PREFECT_REDIS_MESSAGING_HOST}
      - PREFECT_REDIS_MESSAGING_PORT=${PREFECT_REDIS_MESSAGING_PORT}
    networks:
      - backend
# Docker Volumes
volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
  backups:
    driver: local
  pgadmin:
    driver: local

# Docker Network
networks:
  backend:
    name: backend
